---
- name: "Start NGINX (outside docker)"
  when: not IS_DOCKER
  ansible.builtin.service:
    name: nginx
    state: started
- name: "Start NGINX (inside docker)"
  when: IS_DOCKER
  ansible.builtin.command:
    cmd: nginx
  register: nginx_start
  changed_when: nginx_start.rc == 0
  failed_when: "nginx_start.rc != 0 and 'Address already in use' not in nginx_start.stderr"
- name: "Reload NGINX (outside docker)"
  when: not IS_DOCKER
  ansible.builtin.service:
    name: nginx
    state: reloaded
- name: "Reload NGINX (inside docker)"
  when: IS_DOCKER
  ansible.builtin.command:
    cmd: nginx -s reload
  register: nginx_start
